### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by sweetSneak** [cypher-network/cypher#46]
Debug: KeyNotFoundException

SOme testers are reporting issues when starting serf after removing keys and stroredb folders.

Possible causes:
1. Serf is already running.
2. Serf is listening on ports 7946/7373
3. Deduplicate name assigned
4. Other

**Comment by stephankempkes** [comment]
This is most likely due to Serf agents missing the "pubkey" key in the tags dictionary and not checking for the existence of this key before getting the value in https://github.com/cypher-network/cypher/blob/9fcf1bafb3868628a1193cdbf3ffcd8c0814cd57/cypcore/Network/LocalNode.cs#L137

**Comment by stephankempkes** [comment]
Fixed in https://github.com/cypher-network/cypher/pull/53
