### ISSUE TITLE
Fork choice rule

### ISSUE THREAD

**Issue by sweetSneak** [cypher-network/cypher#47]
Work: Does the implementation follow the rules.

An honest node follows a fork choice rule prescribed in the protocol. The purpose is to reach a consensus on which chain of blocks to maintain, in a distributed manner. Eventually, such chosen chain of blocks produces a final ledger of transactions. Under the Nakamoto protocol, a node appends the next generated block to the longest chain in its local view of the block tree. Unlike PoW systems, Nakamoto protocol can lead to serious security issues for PoS systems.

At any given time slot, an honest node keeps track of one main chain that it appends its next generated block to. Upon receiving a new chain of blocks, it needs to decide which chain to keep. Instead of comparing the length of those two chains, as in Nakamoto protocol, we compare the creation time of the first s blocks after the fork in truncated versions of those two chains. Let b-fork be the block where those two chains fork. The honest node counts how long it takes in each chain to create, up to `s` blocks after the fork. The chain with a shorter time for those `s` blocks is chosen, and the next generated block will be appended to the newest block in that selected chain.

One caveat is that we only apply this s-truncation when comparing two chains that both have at least s blocks after those two chains forked. If one of the chains has fewer `s` blocks after forking, we use the longest chain rule to determine which chain to append on. This is necessary in order to ensure that s-truncation is only applied to chains with enough blocks.

**Comment by stephankempkes** [comment]
After discussion with @pingpongsneak, the following will be changed:

**Synchronization**
- Currently a sync is started with a remote node, when the local block height is different from the remote block height. This could lead to parallel chains which go unnoticed for too long. A check based on latest block hash will be added. It might actually be sufficient to only check the latest block hash and skip checking the block height.

- Currently the local block repository is updated node by node. This will be changed to fetching all remote node's chains, pick the chain backed by >50% of all nodes, and only then update the local chain.

**Fork choice rule**
- Currently no blocks are removed from the local repository when another "winning" chain is added. The repository shall only contain the actual main chain, therefore the losing branch from the fork will be removed from the repository.

**Comment by stephankempkes** [comment]
Implementation being done in https://github.com/cypher-network/cypher/tree/feat_sync-sync_last_block_hash

**Comment by stephankempkes** [comment]
As discussed with @pingpongsneak and @sweetSneak : there can be no fork in an honest node, given that at a maximum of 1/3rd of the network are malicious nodes. When bootstrapping the blockchain, this forking rule also does not apply. There are measures in place to make sure >50% of all nodes agree on the bootstrapped chain. Further improvements are possible by anchoring to trusted nodes (for example the seednode) and validating block hashes during synchronization with other nodes.

Closing this issue for now, as the bootstrapping is improved and forking removed.
