### ISSUE TITLE
Cypher Install Scripts

### ISSUE THREAD

**Issue by sweetSneak** [cypher-network/cypher#50]
Finish: https://github.com/cypher-network/cypher/tree/sk_installer

Note: RocksDB requires libc6-dev installed on the Linux OS.

**Comment by stephankempkes** [comment]
https://github.com/cypher-network/cypher/pull/59
- self-contained builds for all supported platforms
- sha256 for each artifact

https://github.com/cypher-network/cypher/pull/60
- debconfig for .deb creation
- systemd service
- no config overwrite

TODO:
- .deb creation for each platform
- check changelog with github release action version; cancel release on mismatch
- merge configuration tool from https://github.com/cypher-network/cypher/tree/sk_cypnode_tester and invoke at installation
- merge generic .sh installer for "non-Debian" systems and macOS from https://github.com/cypher-network/cypher/tree/sk_installer
- installation documentation for Debian + "non-Debian" systems
- installation documentation for Windows
- installation documentation for macOS

WON'T DO:
- support for non-systemd systems: users with different systems can provide tested scripts which will be added to the installer
